version: '3.8'
services:
  app:
    restart: unless-stopped
    container_name: web-app
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - server_network

  nginx:
    restart: unless-stopped
    container_name: web-nginx
    image: nginx
    ports:
      - 3000:3000
    depends_on:
      - app
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - server_network

networks:
  server_network:
